### ISSUE TITLE
The 'redirect_uri' is not authorized

### ISSUE THREAD

**Issue by kaich** [pCloud/pcloud-sdk-swift#2]
I use the sdk. But when I try to authorize. It show a red button with "The 'redirect_uri' is not authorized".  

I only use it in ios. I don't need redirect_uri.  When I add a redirect_uri, It also show "The 'redirect_uri' is not authorized".

I only replace appkey with mine appkey in the demo.
How to deal with it ?

**Comment by tmpit** [comment]
Hello,
You will always need a redirect URI in order to authorize, because the SDK relies on it to intercept the OAuth response. Can you confirm that the redirect URI you have added in the developer console follows the format `pclsdk-w-YOUR_APP_KEY://oauth2redirect` and that `YOUR_APP_KEY` is the string labeled Client ID in the console?

**Comment by kaich** [comment]
@tmpit It's ok. Thank you very much!

**Comment by JoynerPerez1987** [comment]
Please. Give me an example of how to create it

**Comment by tmpit** [comment]
Hello,
If you are referring to the redirect URI, you can find instructions under the Getting Started section in the README file. Also, please do not post here because this issue is closed. If you have a problem with the setup process or you find that the documentation is incomplete or incorrect, please open a new issue.

**Comment by spacewaterbear** [comment]
Beware to remove the port in the in the redirect url  =>  https://YOUR_APP_KEY.fief.dev/docs/oauth2-redirect

**Comment by beevabeeva** [comment]
@spacewaterbear saved me! thank you
